export const ADD_LOGIN_REQUEST="ADD_LOGIN_REQUEST"
export const ADD_LOGIN_SUCCESS="ADD_LOGIN_SUCCESS"
export const ADD_LOGIN_FAILURE="ADD_LOGIN_FAILURE"

export const ADD_REGISTER_REQUEST="ADD_REGISTER_REQUEST"
export const ADD_REGISTER_SUCCESS="ADD_REGISTER_SUCCESS"
export const ADD_REGISTER_FAILURE="ADD_REGISTER_FAILURE"

